{"code":"MODULE_NOT_FOUND","level":"error","message":"Uncaught Exception: Cannot find module '../utils/helpers'\nRequire stack:\n- E:\\sebi-guardian-ai\\backend\\src\\controllers\\authController.js\n- E:\\sebi-guardian-ai\\backend\\src\\routes\\authRoutes.js\n- E:\\sebi-guardian-ai\\backend\\src\\index.js","requireStack":["E:\\sebi-guardian-ai\\backend\\src\\controllers\\authController.js","E:\\sebi-guardian-ai\\backend\\src\\routes\\authRoutes.js","E:\\sebi-guardian-ai\\backend\\src\\index.js"],"service":"sebi-guardian-backend","stack":"Error: Cannot find module '../utils/helpers'\nRequire stack:\n- E:\\sebi-guardian-ai\\backend\\src\\controllers\\authController.js\n- E:\\sebi-guardian-ai\\backend\\src\\routes\\authRoutes.js\n- E:\\sebi-guardian-ai\\backend\\src\\index.js\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)\n    at Module._load (node:internal/modules/cjs/loader:1043:27)\n    at Module.require (node:internal/modules/cjs/loader:1298:19)\n    at require (node:internal/modules/helpers:182:18)\n    at Object.<anonymous> (E:\\sebi-guardian-ai\\backend\\src\\controllers\\authController.js:8:25)\n    at Module._compile (node:internal/modules/cjs/loader:1529:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)\n    at Module.load (node:internal/modules/cjs/loader:1275:32)\n    at Module._load (node:internal/modules/cjs/loader:1096:12)\n    at Module.require (node:internal/modules/cjs/loader:1298:19)","timestamp":"2025-08-29 20:14:47"}
{"level":"info","message":"Ethereal test account created: ulehvwy6dkxk4lpg@ethereal.email","service":"sebi-guardian-backend","timestamp":"2025-08-29 20:14:57"}
{"level":"error","message":"Unable to connect to the database:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"sebi-guardian-backend","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (E:\\sebi-guardian-ai\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (E:\\sebi-guardian-ai\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (E:\\sebi-guardian-ai\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:524:28)\n    at Socket.reportStreamError (E:\\sebi-guardian-ai\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-08-29 20:18:32"}
{"level":"error","message":"Unable to connect to the database:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"sebi-guardian-backend","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (E:\\sebi-guardian-ai\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (E:\\sebi-guardian-ai\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (E:\\sebi-guardian-ai\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:524:28)\n    at Socket.reportStreamError (E:\\sebi-guardian-ai\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-08-29 20:20:03"}
{"level":"error","message":"Unable to connect to the database:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"sebi-guardian-backend","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (E:\\sebi-guardian-ai\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (E:\\sebi-guardian-ai\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (E:\\sebi-guardian-ai\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:524:28)\n    at Socket.reportStreamError (E:\\sebi-guardian-ai\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-08-29 20:21:22"}
